name: CI

on:
  push:
    pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install sox and arecord on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y sox alsa-utils
      - name: Install sox on macOS
        if: runner.os == 'macOS'
        run: |
          brew install sox
      - name: Install sox on Windows
        if: runner.os == 'Windows'
        run: |
          choco install sox.portable
      - run: npm ci
      - run: npm test
